### ISSUE TITLE
Redis如果设置了密码怎么设置呢？

### ISSUE THREAD

**Issue by A563185000** [gogobody/TpCache#13]
我的Redis有密码，直接按照那样设置之后，不起作用，因为没有输入密码的地方

**Comment by JIeJaitt** [comment]
> 这个版本没做密码输入， 你可以在TpCache/driver/typecho_redis.class.php 31行之后加上 $this->redis=$this->redis->auth('密码');

通过这个方法调用出了点问题，测试了好几个redis远程库都不行。

非debug模式下的报错：
```
Call to a member function set() on bool
```

typecho debug 报错：
```
Call to a member function get() on bool
Error: Call to a member function get() on bool in /var/task/user/usr/plugins/TpCache/driver/typecho_redis.class.php:56
Stack trace:
#0 /var/task/user/usr/plugins/TpCache/Plugin.php(260): typecho_redis->get('/_1_markdown')
#1 /var/task/user/usr/plugins/TpCache/Plugin.php(511): TpCache_Plugin::getCache('/_1_markdown')
#2 [internal function]: TpCache_Plugin::cache_contentEx('<p>\xE5\xA6\x82\xE6\x9E\x9C\xE6\x82\xA8\xE7\x9C\x8B...', Object(Widget\Archive), NULL)
#3 /var/task/user/var/Typecho/Plugin.php(446): call_user_func_array(Array, Array)
#4 /var/task/user/var/Widget/Base/Contents.php(964): Typecho\Plugin->__call('Widget_Abstract...', Array)
#5 /var/task/user/var/Typecho/Widget.php(395): Widget\Base\Contents->___content()
#6 /var/task/user/var/Widget/Base/Contents.php(642): Typecho\Widget->__get('content')
#7 /var/task/user/var/Widget/Archive.php(798): Widget\Base\Contents->content('- \xE9\x98\x85\xE8\xAF\xBB\xE5\x89\xA9\xE4\xBD\x99\xE9...')
#8 /var/task/user/usr/themes/default/index.php(36): Widget\Archive->content('- \xE9\x98\x85\xE8\xAF\xBB\xE5\x89\xA9\xE4\xBD\x99\xE9...')
#9 /var/task/user/var/Widget/Archive.php(1418): require_once('/var/task/user/...')
#10 /var/task/user/var/Typecho/Router.php(99): Widget\Archive->render()
#11 /var/task/user/index.php(23): Typecho\Router::dispatch()
#12 {main}
```

**Comment by JIeJaitt** [comment]
@0xabz 老哥，这个方法你试成了嘛？
